name: Release

on:
  push:
    branches:
      - master
      - develop

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: npm install
      - name: Release app
        if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm run release
      - name: Build app without release
        if: github.ref != 'refs/heads/master'
        run: npm run buildLocal
